# Лабораторная работа №8: Проведение исследований с моделями обнаружения и распознавания объектов (Ultralytics YOLO)

## 1. Выбор начальных условий

### 1.a. Выбор набора данных и обоснование

Для данной лабораторной работы был выбран набор данных **COCO128**. Это небольшой, но репрезентативный поднабор данных из известного датасета COCO (Common Objects in Context).

**Обоснование выбора:**
1.  **Доступность и простота использования:** COCO128 поставляется вместе с Ultralytics YOLO, что упрощает его загрузку и использование без необходимости ручной подготовки данных.
2.  **Реальная практическая задача:** Обнаружение объектов на изображениях является фундаментальной задачей компьютерного зрения с множеством практических применений:
    *   **Автономное вождение:** Обнаружение пешеходов, автомобилей, дорожных знаков.
    *   **Видеонаблюдение и безопасность:** Идентификация подозрительных объектов или действий.
    *   **Розничная торговля:** Анализ поведения покупателей, управление запасами (например, подсчет товаров на полках).
    *   **Медицина:** Обнаружение аномалий на медицинских снимках (например, опухолей).
    *   **Сельское хозяйство:** Мониторинг состояния посевов, подсчет скота.
3.  **Разнообразие классов:** Несмотря на небольшой размер, COCO128 содержит изображения с объектами различных классов (80 классов из оригинального COCO), что позволяет обучать и тестировать модели на разнообразных сценариях.
4.  **Подходит для демонстрации:** Малый размер датасета позволяет быстро проводить эксперименты, обучать модели и получать результаты в рамках лабораторной работы, не требуя значительных вычислительных ресурсов или времени.
5.  **Стандартный формат аннотаций:** Данные представлены в формате YOLO, который является стандартом де-факто для многих моделей обнаружения объектов.

Таким образом, COCO128 представляет собой удобный и релевантный датасет для изучения и экспериментирования с моделями обнаружения объектов семейства YOLO.

### 1.b. Выбор метрик качества и обоснование

Для оценки качества моделей обнаружения объектов будут использоваться следующие метрики:

1.  **Precision (Точность):**
    *   Формула: `Precision = TP / (TP + FP)`_
    *   Описание: Доля правильно идентифицированных положительных объектов среди всех объектов, которые модель классифицировала как положительные. Отвечает на вопрос: "Из всех объектов, которые модель назвала 'объектом X', сколько действительно являются 'объектом X'?"
    *   Обоснование: Важна, когда цена ложноположительных срабатываний высока (например, в системах безопасности, где ложная тревога может привести к ненужным действиям).

2.  **Recall (Полнота):**
    *   Формула: `Recall = TP / (TP + FN)`
    *   Описание: Доля правильно идентифицированных положительных объектов среди всех реально существующих положительных объектов. Отвечает на вопрос: "Сколько 'объектов X' из всех реально существующих 'объектов X' модель смогла найти?"
    *   Обоснование: Важна, когда цена ложноотрицательных срабатываний высока (например, в медицине, где пропуск заболевания может иметь серьезные последствия, или при поиске дефектов).

3.  **mAP (mean Average Precision - средняя точность):**
    *   **AP (Average Precision):** Площадь под кривой Precision-Recall для одного класса. AP вычисляется для каждого класса объектов отдельно.
    *   **mAP@0.5 (или mAP50):** Среднее значение AP по всем классам, вычисленное при пороге IoU (Intersection over Union) равном 0.5. IoU измеряет степень пересечения между предсказанной ограничивающей рамкой и истинной рамкой. Порог 0.5 означает, что предсказание считается верным (TP), если IoU > 0.5.
    *   **mAP@0.5:0.95 (или mAP):** Среднее значение AP по всем классам, вычисленное для различных порогов IoU (от 0.5 до 0.95 с шагом 0.05) и затем усредненное. Эта метрика более строгая и дает более комплексную оценку качества модели.

    *   Обоснование: mAP является основной и наиболее комплексной метрикой для задач обнаружения объектов. Она учитывает как точность, так и полноту модели для каждого класса, а также качество локализации объектов (через IoU). mAP@0.5:0.95 дает наиболее объективную оценку общей производительности модели в различных условиях.

**Выбор данных метрик обусловлен их широким распространением в области обнаружения объектов, способностью комплексно оценивать как классификационную, так и локализационную точность модели.**



In [1]:
# Установка Ultralytics
!pip install ultralytics -q
!pip install roboflow -q # На всякий случай, если понадобится для другого датасета


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 28.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 125.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 90.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 54.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 13.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 103.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.4/85.4 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66

In [2]:
import ultralytics
from ultralytics import YOLO
import cv2
import matplotlib.pyplot as plt
import numpy as np
import os
import shutil
import yaml # Для работы с YAML файлами датасета

# Проверка установки
ultralytics.checks()

# Глобальные переменные для хранения результатов
results_history = {}


Ultralytics 8.3.139 🚀 Python-3.11.12 torch-2.6.0+cu124 CUDA:0 (Tesla T4, 15095MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 41.5/112.6 GB disk)


## 2. Создание бейзлайна и оценка качества

На этом этапе мы обучим одну из стандартных моделей YOLO (например, YOLOv8n - nano, самую маленькую и быструю) на нашем наборе данных `coco128.yaml` с базовыми настройками. Это будет наш бейзлайн.

### 2.a. Обучение "коробочной" модели YOLO из Ultralytics
Будем использовать YOLOv8n (nano) как самую быструю для демонстрации
epochs можно поставить поменьше для скорости, например 10-25 для лабораторной
Для реальных задач нужно больше, например, 100-300.
imgsz - размер изображений, на которых обучается модель


In [3]:
 # Задаем параметры
dataset_yaml = 'coco128.yaml' # Стандартный датасет Ultralytics, загрузится автоматически
baseline_model_name = 'yolov8n.pt' # Используем предварительно обученную модель yolov8n
baseline_epochs = 25 # Уменьшим для скорости выполнения лабораторной
baseline_imgsz = 640
baseline_project_name = 'coco128_baseline'
baseline_experiment_name = 'yolov8n_baseline_run'

print(f"Обучение бейзлайн модели: {baseline_model_name}")
print(f"Датасет: {dataset_yaml}")
print(f"Количество эпох: {baseline_epochs}")
print(f"Размер изображения: {baseline_imgsz}")

# Создаем модель
model_baseline = YOLO(baseline_model_name)

# Обучение модели
# device=0 означает использование первого доступного GPU, если есть, иначе CPU.
# В Colab это обычно GPU Tesla T4, K80 и т.д.
try:
    history_baseline = model_baseline.train(
        data=dataset_yaml,
        epochs=baseline_epochs,
        imgsz=baseline_imgsz,
        project=baseline_project_name,
        name=baseline_experiment_name,
        exist_ok=True, # Перезаписывать, если эксперимент уже существует
        patience=5 # Ранняя остановка, если нет улучшений в течение 5 эпох
    )
    print("Обучение бейзлайн модели завершено.")
    baseline_weights_path = os.path.join(baseline_project_name, baseline_experiment_name, 'weights', 'best.pt')
    print(f"Лучшие веса сохранены в: {baseline_weights_path}")

except Exception as e:
    print(f"Ошибка во время обучения бейзлайн модели: {e}")
    # В случае ошибки (например, нет GPU или битая установка)
    # можно попробовать device='cpu' или уменьшить batch size (batch=-1 для автоподбора)
    # history_baseline = model_baseline.train(data=dataset_yaml, epochs=baseline_epochs, imgsz=baseline_imgsz, device='cpu', batch=8) # Пример для CPU
    history_baseline = None # или какое-то значение по умолчанию/обработка
    baseline_weights_path = None



Обучение бейзлайн модели: yolov8n.pt
Датасет: coco128.yaml
Количество эпох: 25
Размер изображения: 640


100%|██████████| 6.25M/6.25M [00:00<00:00, 107MB/s]

Ultralytics 8.3.139 🚀 Python-3.11.12 torch-2.6.0+cu124 CUDA:0 (Tesla T4, 15095MiB)


engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=coco128.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=25, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=yolov8n_baseline_run, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=5, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=coco128_baseline, rect=False, resume=False, retina_masks=

100%|██████████| 6.66M/6.66M [00:00<00:00, 108MB/s]
Unzipping /content/datasets/coco128.zip to /content/datasets/coco128...: 100%|██████████| 263/263 [00:00<00:00, 3420.39file/s]

Dataset download success ✅ (0.8s), saved to /content/datasets



100%|██████████| 755k/755k [00:00<00:00, 22.0MB/s]


                   from  n    params  module                                       arguments                     
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]                 
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]                
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]             
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]                
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]             
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]               
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]           
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128

Model summary: 129 layers, 3,157,200 parameters, 3,157,184 gradients, 8.9 GFLOPs

Transferred 355/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...


100%|██████████| 5.35M/5.35M [00:00<00:00, 83.1MB/s]


AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 788.6±469.6 MB/s, size: 50.9 KB)


train: Scanning /content/datasets/coco128/labels/train2017... 126 images, 2 backgrounds, 0 corrupt: 100%|██████████| 128/128 [00:00<00:00, 2643.10it/s]

train: New cache created: /content/datasets/coco128/labels/train2017.cache


albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 526.9±110.5 MB/s, size: 52.5 KB)


val: Scanning /content/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|██████████| 128/128 [00:00<?, ?it/s]


Plotting labels to coco128_baseline/yolov8n_baseline_run/labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.000119, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to coco128_baseline/yolov8n_baseline_run
Starting training for 25 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       1/25       2.6G      1.156      1.519      1.226        172        640: 100%|██████████| 8/8 [00:03<00:00,  2.14it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.92it/s]

                   all        128        929      0.649      0.536      0.613      0.454



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       2/25      3.53G      1.209      1.436      1.243        231        640: 100%|██████████| 8/8 [00:02<00:00,  3.59it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.55it/s]

                   all        128        929      0.651      0.558      0.629      0.472



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       3/25      3.56G       1.16      1.366      1.252        192        640: 100%|██████████| 8/8 [00:01<00:00,  4.72it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.65it/s]

                   all        128        929      0.647       0.59      0.647      0.483



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       4/25      3.57G      1.164       1.31      1.227        215        640: 100%|██████████| 8/8 [00:02<00:00,  3.88it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.70it/s]

                   all        128        929      0.672      0.577      0.656       0.49



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       5/25      3.58G      1.187      1.312      1.263        236        640: 100%|██████████| 8/8 [00:01<00:00,  4.49it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.00it/s]

                   all        128        929      0.693      0.581      0.673      0.504



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       6/25      3.59G      1.182      1.287      1.229        253        640: 100%|██████████| 8/8 [00:02<00:00,  2.86it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.22it/s]

                   all        128        929      0.667      0.624      0.686      0.518



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       7/25      3.59G      1.084      1.204      1.195        282        640: 100%|██████████| 8/8 [00:01<00:00,  4.64it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.11it/s]

                   all        128        929      0.689      0.635      0.694      0.524



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       8/25      3.59G      1.123      1.204      1.203        192        640: 100%|██████████| 8/8 [00:01<00:00,  4.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.02it/s]

                   all        128        929      0.738      0.642      0.714      0.542



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       9/25      3.59G      1.105      1.107      1.187        180        640: 100%|██████████| 8/8 [00:01<00:00,  4.35it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.61it/s]

                   all        128        929      0.704      0.657      0.722      0.554



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      10/25      3.59G      1.065      1.121      1.155        180        640: 100%|██████████| 8/8 [00:01<00:00,  4.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.92it/s]

                   all        128        929      0.745      0.644      0.727      0.559



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      11/25      3.59G      1.078        1.1      1.171        263        640: 100%|██████████| 8/8 [00:01<00:00,  4.51it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.96it/s]

                   all        128        929      0.771      0.653       0.74      0.568



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      12/25      3.61G      1.099      1.135      1.179        176        640: 100%|██████████| 8/8 [00:01<00:00,  4.83it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.81it/s]

                   all        128        929       0.79      0.651      0.749      0.575



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      13/25      3.61G      1.095      1.085       1.18        251        640: 100%|██████████| 8/8 [00:01<00:00,  4.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.24it/s]

                   all        128        929      0.812       0.65      0.761      0.583



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      14/25      3.63G      1.033       1.05      1.153        208        640: 100%|██████████| 8/8 [00:01<00:00,  4.58it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.05it/s]

                   all        128        929      0.827      0.654      0.768      0.589



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      15/25      3.63G      1.044      1.045       1.14        251        640: 100%|██████████| 8/8 [00:02<00:00,  3.97it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.16it/s]

                   all        128        929      0.805      0.677      0.772      0.589


Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      16/25      3.63G      1.112      1.138      1.152         95        640: 100%|██████████| 8/8 [00:02<00:00,  2.68it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.79it/s]

                   all        128        929      0.811      0.676      0.775       0.59



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      17/25      3.63G      1.099      1.099      1.151        104        640: 100%|██████████| 8/8 [00:02<00:00,  3.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.15it/s]

                   all        128        929       0.79      0.693      0.777      0.591



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      18/25      3.63G      1.036      1.053       1.15        102        640: 100%|██████████| 8/8 [00:01<00:00,  4.80it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.04it/s]

                   all        128        929      0.778      0.701      0.778      0.594



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      19/25      3.63G      1.064      1.031      1.127        139        640: 100%|██████████| 8/8 [00:01<00:00,  4.74it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.80it/s]

                   all        128        929      0.756      0.713      0.781      0.596



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      20/25      3.63G      1.021     0.9981      1.115         94        640: 100%|██████████| 8/8 [00:01<00:00,  4.66it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.60it/s]

                   all        128        929      0.757      0.708      0.781      0.598



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      21/25      3.63G      1.079      1.029      1.157        127        640: 100%|██████████| 8/8 [00:01<00:00,  4.61it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.93it/s]

                   all        128        929       0.75      0.711      0.783      0.599



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      22/25      3.63G      1.027     0.9785      1.115         79        640: 100%|██████████| 8/8 [00:01<00:00,  4.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.05it/s]

                   all        128        929      0.735      0.723      0.783      0.599



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      23/25      3.63G      1.061     0.9803      1.113         99        640: 100%|██████████| 8/8 [00:01<00:00,  4.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.05it/s]

                   all        128        929      0.734      0.739      0.785      0.603



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      24/25      3.63G      1.032     0.9629      1.123        118        640: 100%|██████████| 8/8 [00:01<00:00,  4.05it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.65it/s]

                   all        128        929      0.729      0.742      0.787      0.604



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      25/25      3.63G      1.049     0.9869      1.117        133        640: 100%|██████████| 8/8 [00:01<00:00,  4.71it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.98it/s]

                   all        128        929      0.714      0.742      0.785      0.602



25 epochs completed in 0.025 hours.
Optimizer stripped from coco128_baseline/yolov8n_baseline_run/weights/last.pt, 6.5MB
Optimizer stripped from coco128_baseline/yolov8n_baseline_run/weights/best.pt, 6.5MB

Validating coco128_baseline/yolov8n_baseline_run/weights/best.pt...
Ultralytics 8.3.139 🚀 Python-3.11.12 torch-2.6.0+cu124 CUDA:0 (Tesla T4, 15095MiB)
Model summary (fused): 72 layers, 3,151,904 parameters, 0 gradients, 8.7 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]


                   all        128        929      0.724       0.74      0.786      0.602
                person         61        254       0.87      0.686      0.808      0.601
               bicycle          3          6      0.726      0.333      0.512      0.401
                   car         12         46      0.621      0.261      0.412      0.236
            motorcycle          4          5      0.768        0.8      0.938      0.787
              airplane          5          6      0.781          1      0.948      0.881
                   bus          5          7      0.786      0.714      0.723      0.652
                 train          3          3      0.575          1      0.995      0.886
                 truck          5         12      0.822        0.5      0.592      0.413
                  boat          2          6      0.636      0.667      0.636      0.396
         traffic light          4         14      0.542      0.143      0.205      0.151
             stop sig

### 2.b. Оценка качества модели (бейзлайн) по выбранным метрикам
Оценка будет проводиться на валидационном наборе данных, указанном в coco128.yaml


In [4]:
 if baseline_weights_path and os.path.exists(baseline_weights_path):
    print(f"Оценка бейзлайн модели с весами: {baseline_weights_path}")
    # Загружаем лучшую модель, полученную после обучения
    model_eval_baseline = YOLO(baseline_weights_path)

    # Проводим оценку (валидацию)
    # split='val' по умолчанию, verbose=True для вывода метрик по классам
    metrics_baseline = model_eval_baseline.val(
        data=dataset_yaml,
        imgsz=baseline_imgsz,
        split='val',
        project=baseline_project_name,
        name=baseline_experiment_name + "_eval",
        exist_ok=True
    )
    print("\nРезультаты оценки бейзлайн модели:")
    if metrics_baseline:
      print(f"  Precision(B): {metrics_baseline.box.mp:.4f}") # mP средняя точность по всем классам
      print(f"  Recall(B): {metrics_baseline.box.mr:.4f}")    # mR средняя полнота по всем классам
      print(f"  mAP50(B): {metrics_baseline.box.map50:.4f}")
      print(f"  mAP50-95(B): {metrics_baseline.box.map:.4f}") # Основная метрика mAP

      results_history['baseline'] = {
          'model': baseline_model_name.split('.')[0],
          'weights': baseline_weights_path,
          'precision': metrics_baseline.box.mp,
          'recall': metrics_baseline.box.mr,
          'mAP50': metrics_baseline.box.map50,
          'mAP50-95': metrics_baseline.box.map
      }
    else:
        print("Не удалось получить метрики для бейзлайн модели.")
        results_history['baseline'] = {
          'model': baseline_model_name.split('.')[0],
          'weights': "N/A",
          'precision': 0, 'recall': 0, 'mAP50': 0, 'mAP50-95': 0
        }

    # Показать примеры предсказаний
    # val_results_path = os.path.join(baseline_project_name, baseline_experiment_name + "_eval")
    # print(f"Результаты валидации (изображения с рамками) сохранены в: {val_results_path}")
    # # Показать первые несколько изображений с предсказаниями (если они были сохранены)
    # pred_images = [os.path.join(val_results_path, img) for img in os.listdir(val_results_path) if img.endswith(('.png', '.jpg', '.jpeg'))][:3]
    # for img_path in pred_images:
    #     plt.figure(figsize=(8,8))
    #     plt.imshow(cv2.cvtColor(cv2.imread(img_path), cv2.COLOR_BGR2RGB))
    #     plt.title(os.path.basename(img_path))
    #     plt.axis('off')
    #     plt.show()

else:
    print("Файл с весами бейзлайн модели не найден. Оценка невозможна.")
    results_history['baseline'] = {
          'model': baseline_model_name.split('.')[0],
          'weights': "N/A",
          'precision': 0, 'recall': 0, 'mAP50': 0, 'mAP50-95': 0
    }


Оценка бейзлайн модели с весами: coco128_baseline/yolov8n_baseline_run/weights/best.pt
Ultralytics 8.3.139 🚀 Python-3.11.12 torch-2.6.0+cu124 CUDA:0 (Tesla T4, 15095MiB)
Model summary (fused): 72 layers, 3,151,904 parameters, 0 gradients, 8.7 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1041.3±367.7 MB/s, size: 53.4 KB)


val: Scanning /content/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|██████████| 128/128 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:02<00:00,  2.95it/s]


                   all        128        929      0.763      0.728      0.786      0.605
                person         61        254      0.899      0.669      0.811      0.601
               bicycle          3          6      0.754      0.333      0.542      0.431
                   car         12         46      0.792      0.261      0.434       0.24
            motorcycle          4          5      0.802        0.8      0.938      0.787
              airplane          5          6      0.794          1      0.948      0.882
                   bus          5          7      0.806      0.714      0.723      0.673
                 train          3          3      0.592          1      0.995      0.886
                 truck          5         12      0.861        0.5      0.581      0.414
                  boat          2          6      0.745       0.49      0.648      0.405
         traffic light          4         14      0.563      0.143      0.206      0.151
             stop sig

## 3. Улучшение бейзлайна

На этом этапе мы попытаемся улучшить результаты бейзлайн-модели.

### 3.a. Формулирование гипотез
1.  **Увеличение количества эпох обучения:** Большее количество эпох может позволить модели лучше настроиться на данные.
2.  **Использование более "тяжелой" модели:** Модели с большим количеством параметров (например, `yolov8s.pt` - small) могут показать лучшее качество за счет большей выразительной способности, но будут обучаться дольше и требовать больше ресурсов.
3.  **Оптимизация гиперпараметров:** Изменение скорости обучения (`lr0`), оптимизатора, или параметров аугментации. Ultralytics YOLO автоматически применяет сильные аугментации, но их можно тонко настроить (например, `degrees`, `translate`, `scale`, `fliplr`, `mosaic`, `mixup`).
4.  **Увеличение размера входного изображения (`imgsz`):** Модели могут лучше распознавать мелкие объекты при большем разрешении, но это увеличивает вычислительную нагрузку.

**Проверяемые гипотезы в рамках данной работы:**
*   **Гипотеза 1:** Увеличение количества эпох обучения (с `baseline_epochs` до `improved_epochs`) улучшит метрики.
*   **Гипотеза 2:** Использование более крупной модели (`yolov8s.pt` вместо `yolov8n.pt`) при том же (или немного увеличенном) количестве эпох улучшит метрики.
*   **Гипотеза 3 (Комбинированная):** Использование более крупной модели (`yolov8s.pt`) И большего числа эпох (`improved_epochs`) И, возможно, других гиперпараметров (например, изменение `lr0` или включение/отключение `mosaic` аугментации) даст наилучший результат.

Для улучшения бейзлайна выберем **Гипотезу 3** как наиболее перспективную: используем модель `yolov8s.pt`, увеличим количество эпох и, возможно, слегка скорректируем некоторые параметры обучения, если потребуется (но для начала оставим параметры по умолчанию, кроме модели и эпох).

### 3.b. Проверка гипотез (в данном случае, сразу формируем улучшенный бейзлайн)

Cогласно выбранной гипотезе, пробуем yolov8s и больше эпох


In [5]:
improved_model_name = 'yolov8s.pt' # Берем модель побольше
improved_epochs = baseline_epochs + 15 # Увеличиваем количество эпох (например, до 40)
improved_imgsz = baseline_imgsz # Оставим тот же размер изображения для сравнения
improved_project_name = 'coco128_improved'
improved_experiment_name = 'yolov8s_improved_run'

# Мы можем также попробовать изменить learning rate или другие параметры
# Например: lr0=0.001 (стандартное 0.01), optimizer='AdamW' (стандартное SGD или Adam)
# Для демонстрации оставим большинство параметров по умолчанию для yolov8s
# Можно добавить/изменить параметры аугментации, например:
# augment_params = {'degrees': 10, 'translate': 0.15, 'scale': 0.6, 'fliplr': 0.5, 'mosaic': 0.5, 'mixup':0.1}
# и передать их в model.train(**augment_params)

print(f"Обучение улучшенной модели: {improved_model_name}")
print(f"Датасет: {dataset_yaml}")
print(f"Количество эпох: {improved_epochs}")
print(f"Размер изображения: {improved_imgsz}")

Обучение улучшенной модели: yolov8s.pt
Датасет: coco128.yaml
Количество эпох: 40
Размер изображения: 640


### 3.c. Формирование улучшенного бейзлайна
Это уже сделано выбором модели и параметров выше.

### 3.d. Обучение модели с улучшенным бейзлайном


In [6]:
model_improved = YOLO(improved_model_name)

try:
    history_improved = model_improved.train(
        data=dataset_yaml,
        epochs=improved_epochs,
        imgsz=improved_imgsz,
        project=improved_project_name,
        name=improved_experiment_name,
        exist_ok=True,
        patience=10 # Можно увеличить patience для более "тяжелой" модели
        # lr0=0.005, # Пример изменения learning rate
        # mosaic=0.8, # Пример изменения параметра аугментации
    )
    print("Обучение улучшенной модели завершено.")
    improved_weights_path = os.path.join(improved_project_name, improved_experiment_name, 'weights', 'best.pt')
    print(f"Лучшие веса сохранены в: {improved_weights_path}")

except Exception as e:
    print(f"Ошибка во время обучения улучшенной модели: {e}")
    history_improved = None
    improved_weights_path = None


100%|██████████| 21.5M/21.5M [00:00<00:00, 107MB/s] 


Ultralytics 8.3.139 🚀 Python-3.11.12 torch-2.6.0+cu124 CUDA:0 (Tesla T4, 15095MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=coco128.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=40, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8s.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=yolov8s_improved_run, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=10, perspective=0.0, plots=True, pose=12.0, pretrained=Tr

train: Scanning /content/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|██████████| 128/128 [00:00<?, ?it/s]

albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))


val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 399.3±86.5 MB/s, size: 52.5 KB)


val: Scanning /content/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|██████████| 128/128 [00:00<?, ?it/s]


Plotting labels to coco128_improved/yolov8s_improved_run/labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.000119, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to coco128_improved/yolov8s_improved_run
Starting training for 40 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       1/40      3.99G       1.04      1.095      1.182        172        640: 100%|██████████| 8/8 [00:03<00:00,  2.39it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.55it/s]

                   all        128        929      0.814      0.675      0.773      0.598



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       2/40      4.98G      1.073      1.071      1.181        231        640: 100%|██████████| 8/8 [00:02<00:00,  3.32it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.41it/s]

                   all        128        929      0.804      0.699      0.788      0.614



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       3/40      4.99G      1.027      1.015      1.193        192        640: 100%|██████████| 8/8 [00:02<00:00,  2.92it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.57it/s]

                   all        128        929      0.795      0.714      0.791      0.615



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       4/40      4.99G       1.04     0.9511      1.161        215        640: 100%|██████████| 8/8 [00:02<00:00,  3.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.54it/s]

                   all        128        929      0.778      0.736        0.8       0.62



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       5/40      5.03G      1.033     0.9415      1.164        236        640: 100%|██████████| 8/8 [00:02<00:00,  3.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.37it/s]

                   all        128        929       0.76      0.746      0.808      0.632



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       6/40      5.03G      1.019     0.9308      1.142        253        640: 100%|██████████| 8/8 [00:02<00:00,  2.84it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.59it/s]

                   all        128        929      0.797      0.751      0.822       0.65



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       7/40      5.03G     0.9578     0.8358      1.122        282        640: 100%|██████████| 8/8 [00:02<00:00,  3.57it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.55it/s]

                   all        128        929      0.814       0.75      0.832      0.657



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       8/40      5.06G     0.9678     0.8509      1.114        192        640: 100%|██████████| 8/8 [00:02<00:00,  3.40it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.50it/s]

                   all        128        929      0.816      0.765      0.834      0.664



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       9/40      5.06G     0.9502     0.7919      1.096        180        640: 100%|██████████| 8/8 [00:03<00:00,  2.59it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.57it/s]

                   all        128        929      0.814      0.773      0.838      0.671



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      10/40      5.06G     0.9012     0.7908      1.063        180        640: 100%|██████████| 8/8 [00:02<00:00,  3.56it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.55it/s]

                   all        128        929      0.828      0.791      0.857      0.675



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      11/40      5.06G       0.91     0.7581      1.083        263        640: 100%|██████████| 8/8 [00:02<00:00,  3.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.39it/s]

                   all        128        929      0.841      0.797      0.864      0.687



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      12/40      5.06G     0.9488     0.7832      1.093        176        640: 100%|██████████| 8/8 [00:02<00:00,  2.99it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.58it/s]

                   all        128        929      0.858      0.801      0.868      0.694



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      13/40      5.06G      0.906     0.7381      1.085        251        640: 100%|██████████| 8/8 [00:02<00:00,  3.54it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.55it/s]

                   all        128        929      0.869      0.798      0.866        0.7



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      14/40      5.06G     0.8488     0.7117      1.058        208        640: 100%|██████████| 8/8 [00:02<00:00,  3.54it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.55it/s]

                   all        128        929      0.888      0.789      0.871      0.705



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      15/40      5.06G     0.8767     0.7021      1.044        251        640: 100%|██████████| 8/8 [00:02<00:00,  2.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.50it/s]

                   all        128        929      0.885       0.79      0.872      0.713



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      16/40       5.1G     0.9315     0.7448       1.07        189        640: 100%|██████████| 8/8 [00:02<00:00,  3.54it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.33it/s]

                   all        128        929      0.857      0.814      0.873      0.716



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      17/40       5.1G      0.879      0.739      1.064        184        640: 100%|██████████| 8/8 [00:02<00:00,  3.48it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.59it/s]

                   all        128        929      0.908      0.793      0.878      0.724



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      18/40      5.13G     0.8469     0.6685      1.031        208        640: 100%|██████████| 8/8 [00:02<00:00,  2.89it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.32it/s]

                   all        128        929      0.914        0.8      0.883      0.726



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      19/40      5.13G     0.8749     0.6777       1.05        169        640: 100%|██████████| 8/8 [00:02<00:00,  3.54it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.43it/s]

                   all        128        929      0.908      0.813      0.885      0.735



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      20/40      5.17G     0.8322     0.6717      1.037        185        640: 100%|██████████| 8/8 [00:02<00:00,  3.53it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.60it/s]

                   all        128        929      0.911      0.814      0.887      0.737



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      21/40      5.17G      0.822     0.6413      1.026        317        640: 100%|██████████| 8/8 [00:02<00:00,  2.98it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.70it/s]

                   all        128        929      0.911      0.817       0.89      0.742



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      22/40      5.17G     0.8208     0.6457      1.022        255        640: 100%|██████████| 8/8 [00:02<00:00,  3.56it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.54it/s]

                   all        128        929      0.907      0.823      0.894      0.744



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      23/40      5.21G     0.8537     0.6738      1.032        227        640: 100%|██████████| 8/8 [00:02<00:00,  3.49it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.57it/s]

                   all        128        929      0.906      0.829      0.897      0.747



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      24/40      5.21G     0.8029     0.6323      1.027        196        640: 100%|██████████| 8/8 [00:02<00:00,  3.20it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.49it/s]

                   all        128        929      0.905      0.833      0.897       0.75



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      25/40      5.24G     0.8083     0.6218      1.015        244        640: 100%|██████████| 8/8 [00:02<00:00,  3.53it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.63it/s]

                   all        128        929      0.916      0.832      0.898      0.754



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      26/40      5.24G     0.8191     0.6223      1.027        228        640: 100%|██████████| 8/8 [00:02<00:00,  3.15it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.61it/s]

                   all        128        929      0.916      0.833      0.902      0.755



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      27/40      5.24G     0.7912     0.6056       1.01        202        640: 100%|██████████| 8/8 [00:02<00:00,  3.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.49it/s]

                   all        128        929      0.924      0.833      0.905      0.757



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      28/40      5.24G     0.7899     0.6164      1.025        229        640: 100%|██████████| 8/8 [00:02<00:00,  3.55it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.58it/s]

                   all        128        929      0.924      0.839      0.907      0.761



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      29/40      5.24G     0.7972      0.613      1.024        169        640: 100%|██████████| 8/8 [00:02<00:00,  3.50it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.59it/s]

                   all        128        929      0.921      0.843      0.911      0.767



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      30/40      5.24G     0.7777     0.5891      1.004        201        640: 100%|██████████| 8/8 [00:02<00:00,  3.23it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.42it/s]

                   all        128        929      0.926      0.841      0.913       0.77


Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      31/40      5.24G      0.864      0.814      1.007        101        640: 100%|██████████| 8/8 [00:03<00:00,  2.33it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.48it/s]

                   all        128        929      0.869      0.871       0.91      0.764



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      32/40      5.24G      0.897     0.8188      1.038        104        640: 100%|██████████| 8/8 [00:02<00:00,  3.52it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.60it/s]

                   all        128        929      0.924      0.831      0.909      0.759



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      33/40      5.24G     0.8035      0.639      1.001        128        640: 100%|██████████| 8/8 [00:02<00:00,  2.93it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.92it/s]

                   all        128        929      0.922      0.829       0.91      0.756



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      34/40      5.24G     0.8378     0.6799     0.9901        100        640: 100%|██████████| 8/8 [00:02<00:00,  3.55it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.60it/s]

                   all        128        929      0.926      0.827      0.909      0.755



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      35/40      5.24G     0.8128     0.6742     0.9845         97        640: 100%|██████████| 8/8 [00:02<00:00,  3.55it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.61it/s]

                   all        128        929      0.924      0.824      0.909      0.753



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      36/40      5.24G     0.7969     0.6108     0.9923        111        640: 100%|██████████| 8/8 [00:02<00:00,  3.19it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.54it/s]

                   all        128        929      0.929       0.82      0.911      0.757



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      37/40      5.24G     0.7746     0.5731     0.9795        142        640: 100%|██████████| 8/8 [00:02<00:00,  3.58it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.55it/s]

                   all        128        929      0.918      0.826       0.91      0.757



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      38/40      5.24G      0.815     0.6178     0.9839        131        640: 100%|██████████| 8/8 [00:02<00:00,  3.54it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.60it/s]

                   all        128        929      0.923      0.824       0.91      0.754



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      39/40      5.24G     0.8126     0.5824     0.9827        115        640: 100%|██████████| 8/8 [00:02<00:00,  3.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.44it/s]

                   all        128        929      0.924      0.818      0.906      0.752



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      40/40      5.24G      0.762     0.5949     0.9723        161        640: 100%|██████████| 8/8 [00:02<00:00,  3.65it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.57it/s]

                   all        128        929       0.92       0.82      0.905      0.753
EarlyStopping: Training stopped early as no improvement observed in last 10 epochs. Best results observed at epoch 30, best model saved as best.pt.
To update EarlyStopping(patience=10) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.



40 epochs completed in 0.047 hours.
Optimizer stripped from coco128_improved/yolov8s_improved_run/weights/last.pt, 22.6MB
Optimizer stripped from coco128_improved/yolov8s_improved_run/weights/best.pt, 22.6MB

Validating coco128_improved/yolov8s_improved_run/weights/best.pt...
Ultralytics 8.3.139 🚀 Python-3.11.12 torch-2.6.0+cu124 CUDA:0 (Tesla T4, 15095MiB)
Model summary (fused): 72 layers, 11,156,544 parameters, 0 gradients, 28.6 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.48it/s]


                   all        128        929      0.926      0.841      0.913       0.77
                person         61        254       0.97      0.765      0.914      0.735
               bicycle          3          6      0.942      0.833      0.842       0.53
                   car         12         46      0.955      0.463      0.688      0.364
            motorcycle          4          5      0.916          1      0.995      0.904
              airplane          5          6      0.967          1      0.995      0.974
                   bus          5          7      0.939          1      0.995       0.91
                 train          3          3      0.913          1      0.995      0.995
                 truck          5         12      0.901        0.5      0.673      0.484
                  boat          2          6          1      0.713      0.873      0.709
         traffic light          4         14      0.965      0.429      0.465      0.286
             stop sig

### 3.e. Оценка качества модели с улучшенным бейзлайном


In [7]:
if improved_weights_path and os.path.exists(improved_weights_path):
    print(f"Оценка улучшенной модели с весами: {improved_weights_path}")
    model_eval_improved = YOLO(improved_weights_path)

    metrics_improved = model_eval_improved.val(
        data=dataset_yaml,
        imgsz=improved_imgsz,
        split='val',
        project=improved_project_name,
        name=improved_experiment_name + "_eval",
        exist_ok=True
    )

    print("\nРезультаты оценки улучшенной модели:")
    if metrics_improved:
        print(f"  Precision(B): {metrics_improved.box.mp:.4f}")
        print(f"  Recall(B): {metrics_improved.box.mr:.4f}")
        print(f"  mAP50(B): {metrics_improved.box.map50:.4f}")
        print(f"  mAP50-95(B): {metrics_improved.box.map:.4f}")

        results_history['improved'] = {
            'model': improved_model_name.split('.')[0],
            'weights': improved_weights_path,
            'precision': metrics_improved.box.mp,
            'recall': metrics_improved.box.mr,
            'mAP50': metrics_improved.box.map50,
            'mAP50-95': metrics_improved.box.map
        }
    else:
        print("Не удалось получить метрики для улучшенной модели.")
        results_history['improved'] = {
          'model': improved_model_name.split('.')[0],
          'weights': "N/A",
          'precision': 0, 'recall': 0, 'mAP50': 0, 'mAP50-95': 0
        }
else:
    print("Файл с весами улучшенной модели не найден. Оценка невозможна.")
    results_history['improved'] = {
          'model': improved_model_name.split('.')[0],
          'weights': "N/A",
          'precision': 0, 'recall': 0, 'mAP50': 0, 'mAP50-95': 0
    }


Оценка улучшенной модели с весами: coco128_improved/yolov8s_improved_run/weights/best.pt
Ultralytics 8.3.139 🚀 Python-3.11.12 torch-2.6.0+cu124 CUDA:0 (Tesla T4, 15095MiB)
Model summary (fused): 72 layers, 11,156,544 parameters, 0 gradients, 28.6 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1529.0±633.8 MB/s, size: 53.4 KB)


val: Scanning /content/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|██████████| 128/128 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:03<00:00,  2.48it/s]


                   all        128        929      0.923      0.842       0.91      0.767
                person         61        254       0.97      0.768      0.918      0.733
               bicycle          3          6      0.941      0.833      0.841      0.538
                   car         12         46      0.955      0.463      0.678      0.356
            motorcycle          4          5      0.916          1      0.995      0.904
              airplane          5          6      0.967          1      0.995      0.974
                   bus          5          7      0.939          1      0.995      0.898
                 train          3          3      0.913          1      0.995      0.953
                 truck          5         12      0.901        0.5      0.673      0.471
                  boat          2          6      0.904      0.667      0.821      0.593
         traffic light          4         14      0.965      0.429      0.464      0.292
             stop sig

### 3.f. Сравнение результатов моделей с улучшенным бейзлайном в сравнении с результатами из пункта 2


In [8]:
# Вывод таблицы сравнения результатов
print("Сравнение результатов:")
print("--------------------------------------------------------------------------------------------")
print(f"{'Модель':<25} | {'Precision':<10} | {'Recall':<10} | {'mAP@.50':<10} | {'mAP@.50-.95':<12}")
print("--------------------------------------------------------------------------------------------")

if 'baseline' in results_history:
    b = results_history['baseline']
    print(f"{'YOLOv8n (Бейзлайн)':<25} | {b['precision']:.4f}   | {b['recall']:.4f}   | {b['mAP50']:.4f}   | {b['mAP50-95']:.4f}")
else:
    print(f"{'YOLOv8n (Бейзлайн)':<25} | N/A        | N/A        | N/A        | N/A")


if 'improved' in results_history:
    i = results_history['improved']
    print(f"{'YOLOv8s (Улучшенный)':<25} | {i['precision']:.4f}   | {i['recall']:.4f}   | {i['mAP50']:.4f}   | {i['mAP50-95']:.4f}")

    if 'baseline' in results_history and b['mAP50-95'] > 0 : # Проверка, что есть с чем сравнивать
        print("--------------------------------------------------------------------------------------------")
        print("Изменения относительно бейзлайна:")
        precision_diff = (i['precision'] - b['precision']) / b['precision'] * 100 if b['precision'] != 0 else float('inf')
        recall_diff = (i['recall'] - b['recall']) / b['recall'] * 100 if b['recall'] != 0 else float('inf')
        map50_diff = (i['mAP50'] - b['mAP50']) / b['mAP50'] * 100 if b['mAP50'] != 0 else float('inf')
        map_total_diff = (i['mAP50-95'] - b['mAP50-95']) / b['mAP50-95'] * 100 if b['mAP50-95'] != 0 else float('inf')

        print(f"  Δ Precision: {precision_diff:+.2f}%")
        print(f"  Δ Recall: {recall_diff:+.2f}%")
        print(f"  Δ mAP@.50: {map50_diff:+.2f}%")
        print(f"  Δ mAP@.50-.95: {map_total_diff:+.2f}%")

else:
    print(f"{'YOLOv8s (Улучшенный)':<25} | N/A        | N/A        | N/A        | N/A")

print("--------------------------------------------------------------------------------------------")


Сравнение результатов:
--------------------------------------------------------------------------------------------
Модель                    | Precision  | Recall     | mAP@.50    | mAP@.50-.95 
--------------------------------------------------------------------------------------------
YOLOv8n (Бейзлайн)        | 0.7630   | 0.7279   | 0.7858   | 0.6047
YOLOv8s (Улучшенный)      | 0.9231   | 0.8415   | 0.9104   | 0.7671
--------------------------------------------------------------------------------------------
Изменения относительно бейзлайна:
  Δ Precision: +20.99%
  Δ Recall: +15.61%
  Δ mAP@.50: +15.86%
  Δ mAP@.50-.95: +26.86%
--------------------------------------------------------------------------------------------


### 3.g. Выводы по улучшению бейзлайна

По результатам проведенных экспериментов можно сделать следующие выводы:

*   **Исходный бейзлайн (YOLOv8n):** Модель `YOLOv8n` с параметрами обучения (`25` эпох, размер изображения `640x640` – *предполагается на основе типичных настроек из предоставленного ранее ноутбука, уточните если ваши параметры отличались*) показала следующие результаты:
    *   Precision: `0.7630`
    *   Recall: `0.7279`
    *   mAP@0.5: `0.7858`
    *   mAP@0.5:0.95: `0.6047`
    Эти результаты служат отправной точкой для сравнения.

*   **Улучшенный бейзлайн (YOLOv8s):** После применения гипотез по улучшению (использование модели `YOLOv8s`, увеличение количества эпох до `40` – *предполагается на основе типичных настроек `baseline_epochs + 15` из предоставленного ранее ноутбука, уточните если ваши параметры отличались*, при сохранении размера изображения `640x640`), были получены следующие метрики:
    *   Precision: `0.9231`
    *   Recall: `0.8415`
    *   mAP@0.5: `0.9104`
    *   mAP@0.5:0.95: `0.7671`

*   **Сравнение:**
    *   Улучшенная модель показала **значительное улучшение** метрики mAP@0.5:0.95 на `26.86%` по сравнению с бейзлайном.
    *   Метрика mAP@0.5 **улучшилась** на `15.86%`.
    *   Precision **существенно изменилось** c `0.7630` до `0.9231` (рост на `20.99%`), а Recall также **значительно изменилось** c `0.7279` до `0.8415` (рост на `15.61%`).
    *   Гипотеза об использовании более крупной модели (`YOLOv8s` вместо `YOLOv8n`) в сочетании с увеличением числа эпох обучения полностью подтвердилась, что привело к существенному росту всех ключевых метрик качества обнаружения.

*   **Общий вывод:** Предпринятые шаги по улучшению (переход на более крупную архитектуру `YOLOv8s` и увеличение количества эпох обучения) привели к **однозначно положительному** результату, выразившемуся в заметном повышении всех оцениваемых метрик. Это демонстрирует эффективность выбора более мощной модели и достаточного времени для ее обучения на заданном датасете. Для дальнейшего улучшения можно рассмотреть более тонкую настройку гиперпараметров (например, скорости обучения, параметров аугментации), использование еще большего количества эпох или применение более сложных техник аугментации данных.

## 4. Имплементация алгоритма машинного обучения

В контексте Ultralytics YOLO, "самостоятельная имплементация" может означать не создание всей архитектуры с нуля (что является очень объемной задачей), а, например:
1.  Обучение модели YOLO **"с нуля"** (from scratch), используя только YAML-файл конфигурации архитектуры, а не предварительно обученные веса (`.pt` файл). Это позволяет понять процесс обучения без влияния предварительной подготовки на больших датасетах типа COCO.
2.  Создание собственной конфигурации модели (кастомный YAML), изменяя слои, анкеры и т.д. (более сложный вариант).
3.  Реализация кастомного цикла обучения или функции потерь (также продвинутый вариант).

Для данной лабораторной работы мы выберем **первый вариант**: обучим стандартную архитектуру YOLOv8 (например, YOLOv8n) "с нуля", используя ее `.yaml` файл. Это позволит нам сравнить результаты обучения с использованием предобученных весов (fine-tuning) и обучения с случайно инициализированными весами.

### 4.a. "Самостоятельная имплементация" - обучение модели YOLO с нуля (from scratch)

Вместо `yolov8n.pt` (предобученные веса), мы используем `yolov8n.yaml` (определение архитектуры)
Это означает, что модель будет инициализирована случайными весами и обучена только на нашем датасете coco128


In [9]:
 # Задаем параметры для обучения "с нуля"
custom_model_yaml = 'yolov8n.yaml' # Определяет архитектуру, но не веса
# Для обучения с нуля обычно требуется больше эпох, чем для fine-tuning
# Но для демонстрации оставим сопоставимое количество, как у улучшенного бейзлайна
custom_epochs = improved_epochs # Используем то же количество эпох, что и для лучшей модели выше
custom_imgsz = baseline_imgsz # Тот же размер изображения
custom_project_name = 'coco128_custom_scratch'
custom_experiment_name = 'yolov8n_from_scratch_run'

print(f"Обучение 'кастомной' модели (с нуля): {custom_model_yaml}")
print(f"Датасет: {dataset_yaml}")
print(f"Количество эпох: {custom_epochs}")
print(f"Размер изображения: {custom_imgsz}")

Обучение 'кастомной' модели (с нуля): yolov8n.yaml
Датасет: coco128.yaml
Количество эпох: 40
Размер изображения: 640


### 4.b. Обучение имплементированной модели

Создаем модель на основе YAML конфигурации

In [12]:
model_custom_scratch = YOLO(custom_model_yaml) # Загрузка архитектуры

try:
    history_custom_scratch = model_custom_scratch.train(
        data=dataset_yaml,
        epochs=custom_epochs,
        imgsz=custom_imgsz,
        project=custom_project_name,
        name=custom_experiment_name,
        exist_ok=True,
        patience=5 # Установим такое же patience, как в baseline
    )
    print("Обучение 'кастомной' модели (с нуля) завершено.")
    custom_scratch_weights_path = os.path.join(custom_project_name, custom_experiment_name, 'weights', 'best.pt')
    print(f"Лучшие веса сохранены в: {custom_scratch_weights_path}")

except Exception as e:
    print(f"Ошибка во время обучения 'кастомной' модели (с нуля): {e}")
    history_custom_scratch = None
    custom_scratch_weights_path = None


Ultralytics 8.3.139 🚀 Python-3.11.12 torch-2.6.0+cu124 CUDA:0 (Tesla T4, 15095MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=coco128.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=40, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.yaml, momentum=0.937, mosaic=1.0, multi_scale=False, name=yolov8n_from_scratch_run, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=5, perspective=0.0, plots=True, pose=12.0, pretrain

train: Scanning /content/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|██████████| 128/128 [00:00<?, ?it/s]

albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))


val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 385.2±87.7 MB/s, size: 52.5 KB)


val: Scanning /content/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|██████████| 128/128 [00:00<?, ?it/s]


Plotting labels to coco128_custom_scratch/yolov8n_from_scratch_run/labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.000119, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to coco128_custom_scratch/yolov8n_from_scratch_run
Starting training for 40 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       1/40      2.66G      3.453      5.758       4.28        172        640: 100%|██████████| 8/8 [00:02<00:00,  2.84it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.18it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       2/40      2.66G      3.563      5.763      4.299        231        640: 100%|██████████| 8/8 [00:02<00:00,  3.47it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  5.28it/s]


                   all        128        929          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       3/40      2.66G      3.525      5.717      4.266        192        640: 100%|██████████| 8/8 [00:01<00:00,  4.49it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  5.09it/s]


                   all        128        929          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       4/40      2.67G      3.555      5.731      4.259        215        640: 100%|██████████| 8/8 [00:01<00:00,  4.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  5.18it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       5/40      2.68G       3.51      5.685      4.265        236        640: 100%|██████████| 8/8 [00:01<00:00,  4.48it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.86it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       6/40      2.69G      3.569      5.686      4.263        253        640: 100%|██████████| 8/8 [00:02<00:00,  3.33it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.62it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       7/40      2.69G      3.553      5.686      4.231        282        640: 100%|██████████| 8/8 [00:01<00:00,  4.61it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  5.44it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       8/40      2.71G      3.549      5.678      4.237        192        640: 100%|██████████| 8/8 [00:01<00:00,  4.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  5.34it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       9/40      2.71G       3.49      5.686      4.218        180        640: 100%|██████████| 8/8 [00:01<00:00,  4.35it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  5.24it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      10/40      2.73G      3.589      5.648      4.214        180        640: 100%|██████████| 8/8 [00:02<00:00,  3.70it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.08it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      11/40      2.73G      3.565      5.636      4.215        263        640: 100%|██████████| 8/8 [00:01<00:00,  4.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  5.38it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      12/40      2.73G       3.65      5.659      4.198        176        640: 100%|██████████| 8/8 [00:01<00:00,  4.61it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  5.39it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      13/40      2.73G      3.652      5.639      4.192        251        640: 100%|██████████| 8/8 [00:01<00:00,  4.62it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  5.33it/s]


                   all        128        929          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      14/40      2.73G      3.514      5.609      4.193        208        640: 100%|██████████| 8/8 [00:02<00:00,  3.90it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.40it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      15/40      2.73G      3.597      5.585      4.187        251        640: 100%|██████████| 8/8 [00:01<00:00,  4.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  5.00it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      16/40      2.73G      3.631      5.629      4.182        189        640: 100%|██████████| 8/8 [00:01<00:00,  4.34it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  5.48it/s]


                   all        128        929          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      17/40      2.73G      3.505      5.595      4.178        184        640: 100%|██████████| 8/8 [00:01<00:00,  4.47it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  5.47it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      18/40      2.73G      3.581      5.603      4.174        208        640: 100%|██████████| 8/8 [00:01<00:00,  4.51it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.81it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      19/40      2.73G      3.553      5.551      4.171        169        640: 100%|██████████| 8/8 [00:02<00:00,  3.56it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  5.25it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      20/40      2.73G      3.618      5.562      4.162        185        640: 100%|██████████| 8/8 [00:01<00:00,  4.48it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  5.35it/s]


                   all        128        929          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      21/40      2.75G      3.597       5.51      4.158        317        640: 100%|██████████| 8/8 [00:01<00:00,  4.56it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.71it/s]

                   all        128        929   0.000124   5.55e-05   6.23e-05   6.23e-06



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      22/40      2.75G      3.481      5.575      4.158        255        640: 100%|██████████| 8/8 [00:01<00:00,  4.40it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.25it/s]

                   all        128        929   3.17e-05   5.55e-05   1.68e-05   1.68e-06



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      23/40      2.75G       3.56      5.558      4.155        227        640: 100%|██████████| 8/8 [00:02<00:00,  3.48it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.70it/s]

                   all        128        929     0.0141    0.00179    0.00786   0.000795



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      24/40      2.75G      3.519      5.512      4.151        196        640: 100%|██████████| 8/8 [00:01<00:00,  4.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.63it/s]

                   all        128        929    0.00123     0.0019    0.00217   0.000651



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      25/40      2.75G      3.595      5.498      4.147        244        640: 100%|██████████| 8/8 [00:01<00:00,  4.61it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.33it/s]

                   all        128        929    0.00394    0.00477    0.00461    0.00106



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      26/40      2.76G      3.581      5.494      4.144        228        640: 100%|██████████| 8/8 [00:01<00:00,  4.51it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.36it/s]

                   all        128        929    0.00117    0.00483    0.00221   0.000801



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      27/40      2.76G      3.536      5.463      4.136        202        640: 100%|██████████| 8/8 [00:02<00:00,  3.32it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.62it/s]

                   all        128        929      0.269    0.00483    0.00595    0.00169



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      28/40      2.78G      3.448      5.485      4.147        229        640: 100%|██████████| 8/8 [00:01<00:00,  4.52it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.34it/s]

                   all        128        929      0.679    0.00156    0.00543     0.0014



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      29/40      2.78G      3.535      5.476      4.139        169        640: 100%|██████████| 8/8 [00:01<00:00,  4.60it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.31it/s]

                   all        128        929      0.708    0.00156     0.0037   0.000995



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      30/40      2.78G      3.457      5.463      4.137        201        640: 100%|██████████| 8/8 [00:01<00:00,  4.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  4.00it/s]

                   all        128        929      0.756    0.00156    0.00262   0.000725


Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      31/40      2.78G      3.472       5.61      4.136        101        640: 100%|██████████| 8/8 [00:03<00:00,  2.25it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.50it/s]

                   all        128        929      0.725    0.00156    0.00313    0.00077



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      32/40      2.78G      3.516      5.621      4.142        104        640: 100%|██████████| 8/8 [00:01<00:00,  4.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.89it/s]

                   all        128        929       0.77    0.00156    0.00371   0.000838
EarlyStopping: Training stopped early as no improvement observed in last 5 epochs. Best results observed at epoch 27, best model saved as best.pt.
To update EarlyStopping(patience=5) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.



32 epochs completed in 0.029 hours.
Optimizer stripped from coco128_custom_scratch/yolov8n_from_scratch_run/weights/last.pt, 6.5MB
Optimizer stripped from coco128_custom_scratch/yolov8n_from_scratch_run/weights/best.pt, 6.5MB

Validating coco128_custom_scratch/yolov8n_from_scratch_run/weights/best.pt...
Ultralytics 8.3.139 🚀 Python-3.11.12 torch-2.6.0+cu124 CUDA:0 (Tesla T4, 15095MiB)
YOLOv8n summary (fused): 72 layers, 3,151,904 parameters, 0 gradients, 8.7 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.91it/s]


                   all        128        929      0.564    0.00162    0.00593    0.00154
                person         61        254    0.00178    0.00394     0.0034   0.000819
               bicycle          3          6          0          0          0          0
                   car         12         46          0          0          0          0
            motorcycle          4          5          1          0          0          0
              airplane          5          6          1          0          0          0
                   bus          5          7          1          0          0          0
                 train          3          3          1          0          0          0
                 truck          5         12          1          0          0          0
                  boat          2          6          0          0          0          0
         traffic light          4         14          0          0          0          0
             stop sig

### 4.c. Оценка качества имплементированной модели (обученной с нуля)


In [13]:
if custom_scratch_weights_path and os.path.exists(custom_scratch_weights_path):
    print(f"Оценка 'кастомной' модели (с нуля) с весами: {custom_scratch_weights_path}")
    model_eval_custom_scratch = YOLO(custom_scratch_weights_path)

    metrics_custom_scratch = model_eval_custom_scratch.val(
        data=dataset_yaml,
        imgsz=custom_imgsz,
        split='val',
        project=custom_project_name,
        name=custom_experiment_name + "_eval",
        exist_ok=True
    )

    print("\nРезультаты оценки 'кастомной' модели (обученной с нуля):")
    if metrics_custom_scratch:
        print(f"  Precision(B): {metrics_custom_scratch.box.mp:.4f}")
        print(f"  Recall(B): {metrics_custom_scratch.box.mr:.4f}")
        print(f"  mAP50(B): {metrics_custom_scratch.box.map50:.4f}")
        print(f"  mAP50-95(B): {metrics_custom_scratch.box.map:.4f}")

        results_history['custom_scratch'] = {
            'model': custom_model_yaml.split('.')[0] + " (scratch)",
            'weights': custom_scratch_weights_path,
            'precision': metrics_custom_scratch.box.mp,
            'recall': metrics_custom_scratch.box.mr,
            'mAP50': metrics_custom_scratch.box.map50,
            'mAP50-95': metrics_custom_scratch.box.map
        }
    else:
        print("Не удалось получить метрики для 'кастомной' модели (с нуля).")
        results_history['custom_scratch'] = {
          'model': custom_model_yaml.split('.')[0] + " (scratch)",
          'weights': "N/A",
          'precision': 0, 'recall': 0, 'mAP50': 0, 'mAP50-95': 0
        }
else:
    print("Файл с весами 'кастомной' модели (с нуля) не найден. Оценка невозможна.")
    results_history['custom_scratch'] = {
          'model': custom_model_yaml.split('.')[0] + " (scratch)",
          'weights': "N/A",
          'precision': 0, 'recall': 0, 'mAP50': 0, 'mAP50-95': 0
        }

Оценка 'кастомной' модели (с нуля) с весами: coco128_custom_scratch/yolov8n_from_scratch_run/weights/best.pt
Ultralytics 8.3.139 🚀 Python-3.11.12 torch-2.6.0+cu124 CUDA:0 (Tesla T4, 15095MiB)
YOLOv8n summary (fused): 72 layers, 3,151,904 parameters, 0 gradients, 8.7 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1618.9±846.2 MB/s, size: 53.4 KB)


val: Scanning /content/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|██████████| 128/128 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:02<00:00,  3.17it/s]


                   all        128        929      0.482    0.00471    0.00468    0.00102
                person         61        254    0.00629     0.0236    0.00272   0.000669
               bicycle          3          6          0          0          0          0
                   car         12         46          0          0          0          0
            motorcycle          4          5          0          0          0          0
              airplane          5          6          1          0          0          0
                   bus          5          7          1          0          0          0
                 train          3          3          0          0          0          0
                 truck          5         12          1          0          0          0
                  boat          2          6          0          0          0          0
         traffic light          4         14          0          0          0          0
             stop sig

### 4.d. Сравнение результатов имплементированных моделей (обученных с нуля) в сравнении с результатами из пункта 2 (бейзлайн)


In [14]:
print("Сравнение результатов: Бейзлайн vs. Обучение с нуля")
print("--------------------------------------------------------------------------------------------")
print(f"{'Модель':<30} | {'Precision':<10} | {'Recall':<10} | {'mAP@.50':<10} | {'mAP@.50-.95':<12}")
print("--------------------------------------------------------------------------------------------")

if 'baseline' in results_history:
    b = results_history['baseline']
    print(f"{'YOLOv8n (Бейзлайн, fine-tune)':<30} | {b['precision']:.4f}   | {b['recall']:.4f}   | {b['mAP50']:.4f}   | {b['mAP50-95']:.4f}")
else:
    print(f"{'YOLOv8n (Бейзлайн, fine-tune)':<30} | N/A        | N/A        | N/A        | N/A")

if 'custom_scratch' in results_history:
    cs = results_history['custom_scratch']
    print(f"{'YOLOv8n (Кастом, с нуля)':<30} | {cs['precision']:.4f}   | {cs['recall']:.4f}   | {cs['mAP50']:.4f}   | {cs['mAP50-95']:.4f}")

    if 'baseline' in results_history and b['mAP50-95'] > 0 :
        print("--------------------------------------------------------------------------------------------")
        print("Изменения 'с нуля' относительно бейзлайна (fine-tune):")
        precision_diff_cs = (cs['precision'] - b['precision']) / b['precision'] * 100 if b['precision'] != 0 else float('inf')
        recall_diff_cs = (cs['recall'] - b['recall']) / b['recall'] * 100 if b['recall'] != 0 else float('inf')
        map50_diff_cs = (cs['mAP50'] - b['mAP50']) / b['mAP50'] * 100 if b['mAP50'] != 0 else float('inf')
        map_total_diff_cs = (cs['mAP50-95'] - b['mAP50-95']) / b['mAP50-95'] * 100 if b['mAP50-95'] != 0 else float('inf')

        print(f"  Δ Precision: {precision_diff_cs:+.2f}%")
        print(f"  Δ Recall: {recall_diff_cs:+.2f}%")
        print(f"  Δ mAP@.50: {map50_diff_cs:+.2f}%")
        print(f"  Δ mAP@.50-.95: {map_total_diff_cs:+.2f}%")
else:
    print(f"{'YOLOv8n (Кастом, с нуля)':<30} | N/A        | N/A        | N/A        | N/A")

print("--------------------------------------------------------------------------------------------")


Сравнение результатов: Бейзлайн vs. Обучение с нуля
--------------------------------------------------------------------------------------------
Модель                         | Precision  | Recall     | mAP@.50    | mAP@.50-.95 
--------------------------------------------------------------------------------------------
YOLOv8n (Бейзлайн, fine-tune)  | 0.7630   | 0.7279   | 0.7858   | 0.6047
YOLOv8n (Кастом, с нуля)       | 0.4821   | 0.0047   | 0.0047   | 0.0010
--------------------------------------------------------------------------------------------
Изменения 'с нуля' относительно бейзлайна (fine-tune):
  Δ Precision: -36.81%
  Δ Recall: -99.35%
  Δ mAP@.50: -99.40%
  Δ mAP@.50-.95: -99.83%
--------------------------------------------------------------------------------------------


### 4.e. Выводы по сравнению "имплементированной" модели (с нуля) с бейзлайном (fine-tune)

*   **Бейзлайн (fine-tune `yolov8n.pt`):** Модель, дообученная на основе предварительно обученных на COCO весов, показала mAP@0.5:0.95 = `0.6047`.
*   **"Кастомная" модель (train from scratch `yolov8n.yaml`):** Модель той же архитектуры (`YOLOv8n`), но обученная с нуля только на датасете COCO128 (предположительно, с тем же количеством эпох, что и улучшенный бейзлайн, например, `40` эпох – *уточните, если число эпох отличалось*), показала mAP@0.5:0.95 = `0.0010`.

*   **Сравнение:**
    *   Обучение с нуля привело к **катастрофическому ухудшению** качества по сравнению с дообучением (fine-tuning) предварительно обученной модели. Разница в mAP@0.5:0.95 составила `-99.83%` (падение с 0.6047 до 0.0010).
    *   Особенно показательно падение метрики Recall (`-99.35%` с `0.7279` до `0.0047`), что свидетельствует о почти полной неспособности модели, обученной с нуля на таком малом датасете, обнаруживать объекты. Метрика mAP@0.5 также упала на `99.40%`.
    *   Это **ожидаемый результат**, поскольку COCO128 является очень маленьким датасетом. Предварительное обучение на большом и разнообразном наборе данных (полный COCO) дает модели хорошее начальное представление о признаках объектов, что позволяет ей быстрее и качественнее адаптироваться к целевому датасету при дообучении. Обучение с нуля на COCO128, даже с достаточным количеством эпох для fine-tuning более крупной модели, не позволяет модели выучить сколь-нибудь значимые представления объектов.
    *   Результаты не являются неожиданными и полностью соответствуют теории transfer learning.

*   **Общий вывод:** Дообучение (fine-tuning) предобученных моделей является **однозначно предпочтительной** стратегией при работе с небольшими целевыми наборами данных, так как позволяет достичь несравненно лучших результатов по сравнению с обучением "с нуля". Для обучения "с нуля" на малых датасетах, таких как COCO128, даже при сопоставимом или увеличенном количестве эпох, модель не способна эффективно обучиться, что демонстрируют полученные крайне низкие метрики. Это подчеркивает критическую важность использования знаний, полученных на больших датасетах.

### 4.f. Добавление техник из улучшенного бейзлайна (пункт 3c) к "кастомной" модели
В пункте 3с мы определили улучшенный бейзлайн, используя модель `yolov8s.pt` (более крупная архитектура) и увеличенное количество эпох. Попробуем применить аналогичный подход к обучению "с нуля": будем использовать архитектуру `yolov8s.yaml` и такое же количество эпох, как в пункте 3d.

Это означает, что мы будем обучать более крупную модель **с нуля**.

### 4.g. Обучение "кастомной" модели (yolov8s с нуля) с техниками из улучшенного бейзлайна



In [15]:
# Параметры для обучения "кастомной улучшенной" модели (yolov8s.yaml с нуля)
custom_imp_model_yaml = 'yolov8s.yaml' # Более крупная архитектура
custom_imp_epochs = improved_epochs # То же количество эпох, что и в п.3.d
custom_imp_imgsz = improved_imgsz # Тот же размер изображения
custom_imp_project_name = 'coco128_custom_imp_scratch'
custom_imp_experiment_name = 'yolov8s_from_scratch_imp_run'

# Другие параметры (аугментации, lr0 и т.д.) из улучшенного бейзлайна пункта 3
# также могут быть применены здесь, если они были явно заданы там.
# В нашем примере из п.3 мы в основном меняли модель и эпохи.
# model_improved.train(... mosaic=0.8 ...)

print(f"Обучение 'кастомной улучшенной' модели (с нуля): {custom_imp_model_yaml}")
print(f"Датасет: {dataset_yaml}")
print(f"Количество эпох: {custom_imp_epochs}")
print(f"Размер изображения: {custom_imp_imgsz}")

# Создаем модель
model_custom_imp_scratch = YOLO(custom_imp_model_yaml)

try:
    history_custom_imp_scratch = model_custom_imp_scratch.train(
        data=dataset_yaml,
        epochs=custom_imp_epochs,
        imgsz=custom_imp_imgsz,
        project=custom_imp_project_name,
        name=custom_imp_experiment_name,
        exist_ok=True,
        patience=10 # Можно оставить или адаптировать
        # mosaic=0.8, # Если такой параметр был в улучшенном бейзлайне п.3
    )
    print("Обучение 'кастомной улучшенной' модели (с нуля) завершено.")
    custom_imp_scratch_weights_path = os.path.join(custom_imp_project_name, custom_imp_experiment_name, 'weights', 'best.pt')
    print(f"Лучшие веса сохранены в: {custom_imp_scratch_weights_path}")

except Exception as e:
    print(f"Ошибка во время обучения 'кастомной улучшенной' модели (с нуля): {e}")
    history_custom_imp_scratch = None
    custom_imp_scratch_weights_path = None


Обучение 'кастомной улучшенной' модели (с нуля): yolov8s.yaml
Датасет: coco128.yaml
Количество эпох: 40
Размер изображения: 640
Ultralytics 8.3.139 🚀 Python-3.11.12 torch-2.6.0+cu124 CUDA:0 (Tesla T4, 15095MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=coco128.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=40, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8s.yaml, momentum=0.937, mosaic=1.0, multi_scale=False, name=yolov8s_from_scratch_imp_run, nbs=64, nm

train: Scanning /content/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|██████████| 128/128 [00:00<?, ?it/s]

albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))


val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 385.3±144.8 MB/s, size: 52.5 KB)


val: Scanning /content/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|██████████| 128/128 [00:00<?, ?it/s]


Plotting labels to coco128_custom_imp_scratch/yolov8s_from_scratch_imp_run/labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.000119, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to coco128_custom_imp_scratch/yolov8s_from_scratch_imp_run
Starting training for 40 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       1/40      4.28G      3.471      5.764      4.255        172        640: 100%|██████████| 8/8 [00:03<00:00,  2.40it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.52it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       2/40      5.27G      3.547      5.757      4.259        231        640: 100%|██████████| 8/8 [00:02<00:00,  3.24it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.42it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       3/40      5.31G      3.519      5.738      4.245        192        640: 100%|██████████| 8/8 [00:02<00:00,  3.37it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.48it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       4/40      5.34G      3.549      5.736      4.241        215        640: 100%|██████████| 8/8 [00:02<00:00,  3.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.53it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       5/40      5.34G      3.513      5.706      4.261        236        640: 100%|██████████| 8/8 [00:02<00:00,  3.17it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.09it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       6/40      5.34G      3.579      5.702      4.256        253        640: 100%|██████████| 8/8 [00:02<00:00,  3.39it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.55it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       7/40      5.38G      3.565      5.699      4.217        282        640: 100%|██████████| 8/8 [00:02<00:00,  3.51it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.45it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       8/40      5.38G      3.534      5.685      4.219        192        640: 100%|██████████| 8/8 [00:02<00:00,  2.91it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.06it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       9/40      5.42G      3.515      5.697      4.226        180        640: 100%|██████████| 8/8 [00:02<00:00,  3.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.39it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      10/40      5.42G      3.609      5.648      4.204        180        640: 100%|██████████| 8/8 [00:02<00:00,  3.52it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.58it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      11/40      5.42G      3.588      5.629      4.202        263        640: 100%|██████████| 8/8 [00:02<00:00,  3.04it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.43it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      12/40      5.42G      3.659      5.649      4.187        176        640: 100%|██████████| 8/8 [00:02<00:00,  3.56it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.49it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      13/40      5.42G      3.662      5.613      4.183        251        640: 100%|██████████| 8/8 [00:02<00:00,  3.56it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.73it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      14/40      5.42G      3.541      5.606      4.181        208        640: 100%|██████████| 8/8 [00:02<00:00,  3.49it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.47it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      15/40      5.42G      3.615      5.589      4.177        251        640: 100%|██████████| 8/8 [00:02<00:00,  3.49it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.48it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      16/40      5.42G      3.637      5.594      4.169        189        640: 100%|██████████| 8/8 [00:02<00:00,  3.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.33it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      17/40      5.42G      3.521      5.566      4.159        184        640: 100%|██████████| 8/8 [00:02<00:00,  3.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  4.52it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      18/40      5.42G      3.602      5.584       4.16        208        640: 100%|██████████| 8/8 [00:02<00:00,  2.78it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.76it/s]

                   all        128        929          0          0          0          0



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      19/40      5.42G      3.558      5.518       4.14        169        640: 100%|██████████| 8/8 [00:02<00:00,  3.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.67it/s]

                   all        128        929   8.55e-05    0.00166   8.25e-05   3.23e-05



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      20/40      5.42G       3.64      5.484      4.138        185        640: 100%|██████████| 8/8 [00:02<00:00,  3.29it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.61it/s]

                   all        128        929   8.73e-05    0.00177   6.78e-05   2.75e-05



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      21/40      5.42G      3.606      5.446      4.126        317        640: 100%|██████████| 8/8 [00:02<00:00,  3.48it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.69it/s]

                   all        128        929   0.000146       0.01    0.00137   0.000345



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      22/40      5.42G      3.498      5.492      4.129        255        640: 100%|██████████| 8/8 [00:02<00:00,  3.50it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.70it/s]

                   all        128        929   8.13e-05     0.0103   0.000942   0.000278



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      23/40      5.42G      3.598      5.437      4.115        227        640: 100%|██████████| 8/8 [00:02<00:00,  3.15it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.49it/s]

                   all        128        929    0.00359     0.0125    0.00352   0.000736



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      24/40      5.42G      3.564      5.381      4.108        196        640: 100%|██████████| 8/8 [00:02<00:00,  3.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.66it/s]

                   all        128        929     0.0098      0.017     0.0104    0.00229



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      25/40      5.42G      3.624      5.363      4.105        244        640: 100%|██████████| 8/8 [00:02<00:00,  3.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.68it/s]

                   all        128        929    0.00606     0.0183    0.00567    0.00141



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      26/40      5.45G      3.582      5.378      4.099        228        640: 100%|██████████| 8/8 [00:02<00:00,  3.03it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.64it/s]

                   all        128        929    0.00166     0.0193    0.00349   0.000681



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      27/40      5.45G      3.564      5.305       4.08        202        640: 100%|██████████| 8/8 [00:02<00:00,  3.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.68it/s]

                   all        128        929      0.304    0.00764    0.00354   0.000626



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      28/40      5.45G       3.49      5.344      4.091        229        640: 100%|██████████| 8/8 [00:02<00:00,  3.53it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.67it/s]

                   all        128        929      0.327    0.00282    0.00361   0.000808



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      29/40      5.49G      3.556      5.318      4.076        169        640: 100%|██████████| 8/8 [00:02<00:00,  3.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.64it/s]

                   all        128        929      0.331    0.00265    0.00365   0.000749



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      30/40      5.49G      3.508      5.313      4.072        201        640: 100%|██████████| 8/8 [00:02<00:00,  3.50it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.64it/s]

                   all        128        929      0.302    0.00282    0.00372   0.000705


Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      31/40      5.49G      3.502      5.412      4.029        101        640: 100%|██████████| 8/8 [00:04<00:00,  1.73it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.49it/s]

                   all        128        929      0.328    0.00282    0.00259   0.000665



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      32/40      5.49G      3.552      5.416      4.038        104        640: 100%|██████████| 8/8 [00:02<00:00,  3.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.60it/s]

                   all        128        929      0.342    0.00438    0.00263   0.000701



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      33/40      5.49G      3.446      5.363      4.029        128        640: 100%|██████████| 8/8 [00:02<00:00,  3.47it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.54it/s]

                   all        128        929      0.341    0.00438    0.00218   0.000552



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      34/40      5.49G      3.489      5.421      4.033        100        640: 100%|██████████| 8/8 [00:02<00:00,  3.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.60it/s]

                   all        128        929      0.355    0.00438    0.00245   0.000734
EarlyStopping: Training stopped early as no improvement observed in last 10 epochs. Best results observed at epoch 24, best model saved as best.pt.
To update EarlyStopping(patience=10) pass a new patience value, i.e. `patience=300` or use `patience=0` to disable EarlyStopping.



34 epochs completed in 0.050 hours.
Optimizer stripped from coco128_custom_imp_scratch/yolov8s_from_scratch_imp_run/weights/last.pt, 22.6MB
Optimizer stripped from coco128_custom_imp_scratch/yolov8s_from_scratch_imp_run/weights/best.pt, 22.6MB

Validating coco128_custom_imp_scratch/yolov8s_from_scratch_imp_run/weights/best.pt...
Ultralytics 8.3.139 🚀 Python-3.11.12 torch-2.6.0+cu124 CUDA:0 (Tesla T4, 15095MiB)
YOLOv8s summary (fused): 72 layers, 11,156,544 parameters, 0 gradients, 28.6 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.60it/s]


                   all        128        929     0.0098      0.017     0.0104    0.00229
                person         61        254    0.00353       0.15    0.00242     0.0009
               bicycle          3          6          0          0          0          0
                   car         12         46          0          0          0          0
            motorcycle          4          5          0          0          0          0
              airplane          5          6          0          0          0          0
                   bus          5          7        0.5      0.143      0.286     0.0857
                 train          3          3          0          0          0          0
                 truck          5         12          0          0          0          0
                  boat          2          6          0          0          0          0
         traffic light          4         14          0          0          0          0
             stop sig

### 4.h. Оценка качества "кастомной улучшенной" модели (yolov8s с нуля)


In [16]:
if custom_imp_scratch_weights_path and os.path.exists(custom_imp_scratch_weights_path):
    print(f"Оценка 'кастомной улучшенной' модели (с нуля) с весами: {custom_imp_scratch_weights_path}")
    model_eval_custom_imp_scratch = YOLO(custom_imp_scratch_weights_path)

    metrics_custom_imp_scratch = model_eval_custom_imp_scratch.val(
        data=dataset_yaml,
        imgsz=custom_imp_imgsz,
        split='val',
        project=custom_imp_project_name,
        name=custom_imp_experiment_name + "_eval",
        exist_ok=True
    )

    print("\nРезультаты оценки 'кастомной улучшенной' модели (обученной с нуля):")
    if metrics_custom_imp_scratch:
        print(f"  Precision(B): {metrics_custom_imp_scratch.box.mp:.4f}")
        print(f"  Recall(B): {metrics_custom_imp_scratch.box.mr:.4f}")
        print(f"  mAP50(B): {metrics_custom_imp_scratch.box.map50:.4f}")
        print(f"  mAP50-95(B): {metrics_custom_imp_scratch.box.map:.4f}")

        results_history['custom_imp_scratch'] = {
            'model': custom_imp_model_yaml.split('.')[0] + " (scratch, imp)",
            'weights': custom_imp_scratch_weights_path,
            'precision': metrics_custom_imp_scratch.box.mp,
            'recall': metrics_custom_imp_scratch.box.mr,
            'mAP50': metrics_custom_imp_scratch.box.map50,
            'mAP50-95': metrics_custom_imp_scratch.box.map
        }
    else:
        print("Не удалось получить метрики для 'кастомной улучшенной' модели (с нуля).")
        results_history['custom_imp_scratch'] = {
          'model': custom_imp_model_yaml.split('.')[0] + " (scratch, imp)",
          'weights': "N/A",
          'precision': 0, 'recall': 0, 'mAP50': 0, 'mAP50-95': 0
        }
else:
    print("Файл с весами 'кастомной улучшенной' модели (с нуля) не найден. Оценка невозможна.")
    results_history['custom_imp_scratch'] = {
          'model': custom_imp_model_yaml.split('.')[0] + " (scratch, imp)",
          'weights': "N/A",
          'precision': 0, 'recall': 0, 'mAP50': 0, 'mAP50-95': 0
        }


Оценка 'кастомной улучшенной' модели (с нуля) с весами: coco128_custom_imp_scratch/yolov8s_from_scratch_imp_run/weights/best.pt
Ultralytics 8.3.139 🚀 Python-3.11.12 torch-2.6.0+cu124 CUDA:0 (Tesla T4, 15095MiB)
YOLOv8s summary (fused): 72 layers, 11,156,544 parameters, 0 gradients, 28.6 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1624.2±294.9 MB/s, size: 53.4 KB)


val: Scanning /content/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|██████████| 128/128 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 8/8 [00:02<00:00,  3.08it/s]


                   all        128        929    0.00276     0.0149    0.00842    0.00176
                person         61        254    0.00353      0.146    0.00239   0.000861
               bicycle          3          6          0          0          0          0
                   car         12         46          0          0          0          0
            motorcycle          4          5          0          0          0          0
              airplane          5          6          0          0          0          0
                   bus          5          7          0          0          0          0
                 train          3          3          0          0          0          0
                 truck          5         12          0          0          0          0
                  boat          2          6          0          0          0          0
         traffic light          4         14          0          0          0          0
             stop sig

### 4.i. Сравнение результатов "кастомной улучшенной" модели (yolov8s с нуля) с результатами из пункта 3 (улучшенный бейзлайн, yolov8s fine-tune)


In [17]:
print("Сравнение результатов: Улучшенный Бейзлайн (fine-tune) vs. 'Кастомная Улучшенная' (scratch)")
print("----------------------------------------------------------------------------------------------------")
print(f"{'Модель':<40} | {'Precision':<10} | {'Recall':<10} | {'mAP@.50':<10} | {'mAP@.50-.95':<12}")
print("----------------------------------------------------------------------------------------------------")

if 'improved' in results_history: # Это улучшенный бейзлайн из п.3 (yolov8s.pt fine-tune)
    i = results_history['improved']
    print(f"{'YOLOv8s (Улучшенный, fine-tune)':<40} | {i['precision']:.4f}   | {i['recall']:.4f}   | {i['mAP50']:.4f}   | {i['mAP50-95']:.4f}")
else:
    print(f"{'YOLOv8s (Улучшенный, fine-tune)':<40} | N/A        | N/A        | N/A        | N/A")

if 'custom_imp_scratch' in results_history: # Это yolov8s.yaml обученный с нуля с "улучшениями"
    cis = results_history['custom_imp_scratch']
    print(f"{'YOLOv8s (Кастом-Улучш, с нуля)':<40} | {cis['precision']:.4f}   | {cis['recall']:.4f}   | {cis['mAP50']:.4f}   | {cis['mAP50-95']:.4f}")

    if 'improved' in results_history and i['mAP50-95'] > 0:
        print("----------------------------------------------------------------------------------------------------")
        print("Изменения 'кастом-улучш, с нуля' относительно 'улучшенного fine-tune':")
        precision_diff_cis_vs_i = (cis['precision'] - i['precision']) / i['precision'] * 100 if i['precision'] !=0 else float('inf')
        recall_diff_cis_vs_i = (cis['recall'] - i['recall']) / i['recall'] * 100 if i['recall'] !=0 else float('inf')
        map50_diff_cis_vs_i = (cis['mAP50'] - i['mAP50']) / i['mAP50'] * 100 if i['mAP50'] !=0 else float('inf')
        map_total_diff_cis_vs_i = (cis['mAP50-95'] - i['mAP50-95']) / i['mAP50-95'] * 100 if i['mAP50-95'] !=0 else float('inf')

        print(f"  Δ Precision: {precision_diff_cis_vs_i:+.2f}%")
        print(f"  Δ Recall: {recall_diff_cis_vs_i:+.2f}%")
        print(f"  Δ mAP@.50: {map50_diff_cis_vs_i:+.2f}%")
        print(f"  Δ mAP@.50-.95: {map_total_diff_cis_vs_i:+.2f}%")

else:
    print(f"{'YOLOv8s (Кастом-Улучш, с нуля)':<40} | N/A        | N/A        | N/A        | N/A")

print("----------------------------------------------------------------------------------------------------")


Сравнение результатов: Улучшенный Бейзлайн (fine-tune) vs. 'Кастомная Улучшенная' (scratch)
----------------------------------------------------------------------------------------------------
Модель                                   | Precision  | Recall     | mAP@.50    | mAP@.50-.95 
----------------------------------------------------------------------------------------------------
YOLOv8s (Улучшенный, fine-tune)          | 0.9231   | 0.8415   | 0.9104   | 0.7671
YOLOv8s (Кастом-Улучш, с нуля)           | 0.0028   | 0.0149   | 0.0084   | 0.0018
----------------------------------------------------------------------------------------------------
Изменения 'кастом-улучш, с нуля' относительно 'улучшенного fine-tune':
  Δ Precision: -99.70%
  Δ Recall: -98.23%
  Δ mAP@.50: -99.07%
  Δ mAP@.50-.95: -99.77%
----------------------------------------------------------------------------------------------------


### 4.j. Выводы по сравнению "кастомной улучшенной" модели (с нуля) с улучшенным бейзлайном (fine-tune)

*   **Улучшенный бейзлайн (fine-tune `yolov8s.pt`):** Модель `yolov8s`, дообученная на COCO128 с `40` эпохами (*предполагается на основе предыдущих данных, уточните, если ваше M отличалось*), показала mAP@0.5:0.95 = `0.7671`.
*   **"Кастомная улучшенная" модель (train `yolov8s.yaml` from scratch):** Модель архитектуры `yolov8s`, обученная с нуля на COCO128 с `40` эпохами (*те же параметры, что и для улучшенного бейзлайна*), показала mAP@0.5:0.95 = `0.0018`.

*   **Сравнение:**
    *   Даже при использовании более крупной архитектуры (`yolov8s.yaml`) и тех же "улучшенных" параметров обучения (количество эпох), обучение с нуля все еще **катастрофически уступает** дообучению (fine-tuning) модели `yolov8s.pt`. Разница в mAP@0.5:0.95 составила `-99.77%` (падение с `0.7671` до `0.0018`).
    *   Все остальные метрики (Precision, Recall, mAP@0.5) также показали крайне значительное падение (`-99.70%`, `-98.23%`, `-99.07%` соответственно).
    *   Это **полностью подтверждает** предыдущий вывод о критической важности предварительного обучения, особенно для небольших датасетов. Увеличение размера архитектуры при обучении с нуля на малом наборе данных не компенсирует отсутствие знаний, полученных при pre-training на большом датасете. Модель без предварительного обучения не смогла извлечь полезные признаки даже с более сложной архитектурой.

*   **Общий вывод:** Для небольших датасетов, таких как COCO128, использование предварительно обученных весов (fine-tuning) остается наиболее эффективной стратегией для достижения высокого качества моделей обнаружения объектов. Обучение "с нуля", даже с более крупными архитектурами и увеличенным числом эпох, **категорически не позволяет** достичь сколько-нибудь приемлемого уровня производительности без значительного увеличения объема данных или продолжительности обучения. Эксперименты с обучением "с нуля" наглядно демонстрируют ценность transfer learning и сложность обучения глубоких моделей на ограниченных данных.

---

## Общие выводы по лабораторной работе №8

В ходе выполнения лабораторной работы были проведены исследования с моделями обнаружения объектов семейства YOLO (на примере Ultralytics YOLOv8) на датасете COCO128.

1.  **Бейзлайн:** Была обучена базовая модель (`yolov8n.pt` fine-tune) с `25` эпохами (*N, уточните, если ваше значение отличалось*), которая показала результат mAP@0.5:0.95 = `0.6047`.
2.  **Улучшение бейзлайна:** Путем использования более крупной модели `yolov8s.pt` и увеличения числа эпох до `40` (*M, уточните, если ваше значение отличалось*) удалось **значительно улучшить** качество, достигнув mAP@0.5:0.95 = `0.7671`, что на `+26.86%` **лучше** бейзлайна. Это подтвердило гипотезу о том, что выбор более сложной архитектуры и увеличение продолжительности обучения могут положительно сказаться на результате при дообучении.
3.  **"Кастомная" имплементация (обучение с нуля):**
    *   Обучение модели `yolov8n.yaml` с нуля показало mAP@0.5:0.95 = `0.0010`, что значительно (на `99.83%`) **хуже** чем fine-tuning (`yolov8n.pt`). Это подчеркивает критическую важность transfer learning для малых датасетов.
    *   Обучение более крупной модели `yolov8s.yaml` с нуля с "улучшенными" параметрами (аналогично п.2) дало mAP@0.5:0.95 = `0.0018`. Этот результат **все еще катастрофически уступал** (на `99.77%`) fine-tuning модели `yolov8s.pt` (`0.7671`), что **дополнительно и неопровержимо подтверждает** выводы о подавляющем преимуществе fine-tuning на малых датасетах, даже при использовании более мощных архитектур для обучения с нуля.

**Ключевые наблюдения:**
*   **Transfer Learning (Fine-tuning):** Является абсолютно доминирующим и мощным инструментом, особенно при ограниченном объеме целевых данных как COCO128. Использование предобученных весов (`.pt` файлы) дает несравнимо лучший старт и приводит к на порядки более высоким результатам по сравнению с обучением с нуля.
*   **Размер модели и время обучения (при fine-tuning):** Более крупные модели (как `yolov8s` по сравнению с `yolov8n`) в сочетании с достаточным количеством эпох для дообучения могут дать значительный прирост качества.
*   **Обучение с нуля на малых датасетах:** Для сложных задач, таких как обнаружение объектов, и современных глубоких архитектур, обучение с нуля на датасетах размером с COCO128 практически не приводит к формированию работоспособной модели, независимо от размера архитектуры (в разумных пределах) или количества эпох, сопоставимых с fine-tuning.
*   **Датасет:** COCO128 удобен для быстрых экспериментов и демонстрации основных принципов, но его малый размер делает результаты обучения с нуля нерепрезентативными для реальных задач, где такие модели не смогли бы выучить общие признаки.

**Практическая значимость:** Данная работа наглядно демонстрирует стандартный пайплайн работы с моделями обнаружения объектов и критическую важность стратегии transfer learning (fine-tuning) при работе с ограниченными наборами данных. Понимание того, что попытки обучить сложные модели "с нуля" на малых данных скорее всего обречены на неудачу, экономит время и ресурсы, направляя усилия на правильную адаптацию существующих мощных предобученных моделей.